#ifndef __ENUMS_H__

enum SCENE_CHANGE 
{
	SC_NONE, 
	SC_JUSIN,
	SC_LOGO,
	SC_TOWN, 
	SC_DUNGEON_ENTRANCE, 
	SC_STAGE1, 
	SC_STAGE2, 
	SC_STAGE3,
	SC_SHOP,
	SC_BOSS1, 
	SC_EDIT,
	SC_END
};

enum OBJECT_TYPE { OT_FIELD_OBJECT, OT_NPC, OT_MONSTER_PARTICLE, OT_TRESURE_BOX, OT_FIELD_ITEM, OT_PLAYER_BULLET, OT_MONSTER, OT_MONSTER_BOSS, OT_MONSTER_BULLET, OT_PLAYER, OT_END};

enum ITEM_TYPE {IT_WEAPON, IT_SHIELD, IT_ACCESSORIES, IT_GOLD_COIN, IT_END};

enum TILE_TYPE {TT_TILE, TT_OPTION, TT_END};

enum TILE_OPTION_ID 
{
	TO_NONE, 
	TO_NOMOVE_RECT, TO_NOMOVE_RD, TO_NOMOVE_LD, TO_NOMOVE_RU, TO_NOMOVE_LU, 
	TO_NODOWN_RECT, TO_NODOWN_RD, TO_NODOWN_LD, TO_NODOWN_RU, TO_NODOWN_LU,
	TO_NOUP_RECT, 
	TO_NORIGHT_RECT,
	TO_NOLEFT_RECT,
	TO_END
};

enum EQUIP_SLOT
{
	ES_WEAPON1,
	ES_SHIELD1,
	ES_WEAPON2,
	ES_SHIELD2,
	ES_ACCESSORIES1,
	ES_ACCESSORIES2,
	ES_ACCESSORIES3,
	ES_ACCESSORIES4,
	ES_END
};

enum INVEN_SLOT_TYPE
{
	IST_WEAPON1,
	IST_SHIELD1,
	IST_WEAPON2,
	IST_SHIELD2,
	IST_ACCESSORIES1,
	IST_ACCESSORIES2,
	IST_ACCESSORIES3,
	IST_ACCESSORIES4,
	IST_INVEN,
	IST_END
};

enum ANIMATION_TYPE {AT_ONCE, AT_REPEAT, AT_END};

enum FONT_TYPE	{ FT_NORMAL, FT_EDGE, FT_FIELD, FT_FIELD_GOLD, FT_END };

enum FONT_POS_X	{ FPX_LEFT, FPX_CENTER, FPX_RIGHT, FPX_END };
enum FONT_POS_Y { FPY_TOP, FPY_MIDDLE, FPY_BOTTOM, FPY_END };

#define __ENUMS_H__

#endif
